### ISSUE TITLE
💡 Feature request: Safe subscriptions to a local database like SQLite or a simple .txt file.

### ISSUE THREAD

**Issue by mikve97** [ferritreader/ferrit#53]
## Problem

 As I am using a hardened version of Firefox it automatically clears cookies. I think it would be very useful especially for self-hosted instances to safe the subscriptions locally to a file or a simple sqlite database. 

## Request
Safe the subscriptions to a local file or sqlite database so that clearing cookies does not remove your subscriptions.

**Comment by Daniel-Valentine** [comment]
In some sense, we do allow exporting the settings, including subscriptions, by
1. providing a link at the bottom of the settings page  that one can visit to restore settings, of the form `/settings/restore/?theme=[theme]&front_page=[front_page]&layout=[layout]&...`; and
2. setting cookies, although in order to retrieve those settings one would have to inspect the browser cookie jar.

As far as an export file goes, that really isn't useful unless there's some way to import that file into Ferrit. Support for file uploads entails risk, especially given that Ferrit enforces no authentication and by design would allow anyone to upload files. This broadens the attack surface for DoS on Ferrit. Rust is strict about memory management, but there is also the risk of buffer overflow, arbitrary code execution, or memory exhaustion. Therefore, I'm not going to support a file upload interface on Ferrit to import previous settings.

That being said, if the demand is high enough that we allow people to export their settings into a more human-friendly format like JSON, what we could do is an in-browser method for restoring settings, written in Javascript. This would generate a `/settings/restore/` link from those settings and then perform an immediate GET of that link. This would require a user have Javascript enabled though, and I would like to avoid Javascript creep; we should endeavor to have Ferrit be maximally Javascript-free.

**Comment by spikecodes** [comment]
I agree with with Daniel. For the few users who have auto-clear enabled for cookies, the setting export link is a solution currently but it's an edge case not frequent enough to justify the large reworking to switching to a SQLite or .txt storage system.
